### ISSUE TITLE
Update to raylib-5.0

### ISSUE THREAD

**Issue by schveiguy** [D-a-n-i-l-o/raylib-d_examples#1]
Hi Danilo!

I have updated the binding to version 5.0. I don't know if any of the examples need updating. No rush, just wanted to make you aware.

**Comment by D-a-n-i-l-o** [comment]
Thanks @schveiguy! All examples in this repo use raylib-d 5.0.0 now.

Adding some of the new raylib 5 examples is on the to-do list.

**Comment by schveiguy** [comment]
Great!
